### ISSUE TITLE
Support Event.listen()

### ISSUE THREAD

**Issue by cherryleafroad** [elast0ny/raw_sync-rs#5]
(Regarding sharedmem). As it stands now, `event.wait()` waits infinitely, but because of this, it's impossible to tell a thread to stop, and thus let it go out of scope and do cleanup (drop). If it DOES get interrupted somehow, it doesn't get cleaned up, and leaves behind remnants. This is particularly noticeable when pressing ctrl+c. A workaround is to use the [ctrl+c crate](https://crates.io/crates/ctrlc) and setting it up so that it listens for a cue to quit, then exit the infinite loop. For example:

```Rust
let shmem = ShmemConf::new().size(50000000).flink("filename").create().unwrap_or_else(|e| {
    eprint_err(e);
});

//Create an event in the shared memory
let evt = unsafe { Event::new(shmem.as_ptr(), true).unwrap() };

let running = Arc::new(AtomicBool::new(true));
let r = running.clone();

ctrlc::set_handler(move || {
    r.store(false, Ordering::SeqCst);
})

loop {
    let time = Timeout::Val(time::Duration::from_secs(1));
    if let Ok(_) = evt.wait(time) {
        println!("Signal received\n");
    }

    // ctrlc pressed, so break the loop
    if !running.load(Ordering::SeqCst) {
        println!("hit ctrlc break in loop\n");
        break;
    }
}
```

But you can see here that there's a caveat. We have to stop event processing at _some point_ in order to check if we can break the loop. Since you can only receive the event while it's on the blocking call, in this TINY fraction of time, it is possible to miss a signal!!

It would be much more useful if we had something like [event-listener](https://crates.io/crates/event-listener) where you can do a non-blocking `listen`, then check the event, and continue processing other things (like to check for breaks). This would allow maximum performance and near instantaneous response (unlike my solution above which takes at most 1 second to respond to ctrl+c).

--
For an example of the event bring missed, you can change the server code to something like this and see that pretty much all client events are missed unless they coincide with the infinitesimally small 1 millisecond window of opportunity
```Rust
loop {
    let time = Timeout::Val(time::Duration::from_millis(1));
    if let Ok(_) = evt.wait(time) {
        println!("Signal received\n");
    }

    // ctrlc pressed, so break the loop
    if !running.load(Ordering::SeqCst) {
        println!("hit ctrlc break in loop\n");
        break;
    }

  // simulate doing some other random work for 2 seconds
  let more_time = time::Duration::from_secs(2);
  thread::sleep(more_time);
}
```

--
Unfortunately, due to this limitation, it's not even feasible to use another thread, since because of the infinite wait, you can't even pass a message to it to tell it to quit and do cleanup, therefore the only way would be to check for a message and _potentially_ miss an event again (same issue as above)

--
Now, I do suppose there might be another way of doing this which would fix this, but I'm a beginner too (just learned Rust several days ago, with no prior C experience). That being said, this would still make the process more friendly

**Comment by elast0ny** [comment]
Hi,

I'm not 100% sure I understand the issue you're having but I suspect you may have misconceptions about the type of events `raw_sync` provides.

For example, this assumption is wrong :
> We have to stop event processing at some point in order to check if we can break the loop. Since you can only receive the event while it's on the blocking call, in this TINY fraction of time, it is possible to miss a signal

If no one is listening on an event and a process sets the event to being signaled, the event will remain in the signaled state until either someone resets its state or calls `wait()`. There should be no way in which a call to `evt.set(EventState::Signaled)` gets lost because no one else was inside an `evt.wait(t)` call.


### Here are a few things that may be causing confusion : 
Calling `evt.set(EventState::Signaled)` multiple times when no one is blocking on `evt.wait(t)` does not "queue" events, it simply sets the state to signaled which will be undone by a single `evt.wait(t)` call.

Only **one** process blocking on `evt.wait(t)` will get woken up if the event was created with `auto_reset = true`. In other words, a single `evt.set(EventState::Signaled)` will wake up a single process/thread.

If `auto_reset` is set to `false`, then a single `evt.set(EventState::Signaled)` will wake up **every** process/thread that is blocking on an `evt.wait(t)` call. (It also means that this will keep happening until `evt.set(EventState::Clear)` is called)


The behaviors above are what the operating systems provide (both Windows and Linux offer the same default behaviors). All `raw_sync` does is provide a thing Rust wrapper around those OS primitives.

Let me know if this helps !

**Comment by cherryleafroad** [comment]
Hi, it appears something was wrong with my packages (no idea what). I deleted all the cache and downloaded packages, then let it rebuild from scratch, then it worked like you said. Thanks!
